# Generated by Django 5.2.13 on 2026-04-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Evento')),
                ('cliente', models.CharField(max_length=200, verbose_name='Cliente')),
                ('fecha', models.DateField(verbose_name='Fecha del Evento')),
                ('tipo_evento', models.CharField(choices=[('matrimonio', 'Matrimonio'), ('quinceanios', 'Quinceaños'), ('cumpleanios', 'Cumpleaños'), ('graduacion', 'Graduación'), ('bautizo', 'Bautizo'), ('cena_corporativa', 'Cena Corporativa'), ('almuerzo_ejecutivo', 'Almuerzo Ejecutivo'), ('coctel', 'Cóctel'), ('brunch', 'Brunch'), ('buffet', 'Buffet'), ('cafe', 'Café'), ('baby_shower', 'Baby Shower'), ('reunion_familiar', 'Reunión Familiar'), ('otro', 'Otro')], default='otro', max_length=30)),
                ('pax', models.PositiveIntegerField(default=1, verbose_name='Cantidad de Personas')),
                ('lugar', models.CharField(blank=True, default='', max_length=300)),
                ('estado', models.CharField(choices=[('presupuestado', 'Presupuestado'), ('confirmado', 'Confirmado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='presupuestado', max_length=20)),
                ('menu', models.TextField(blank=True, default='', verbose_name='Descripción del Menú')),
                ('observaciones', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ItemPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('categoria', models.CharField(choices=[('I', 'Ingrediente / Insumo'), ('M', 'Mano de Obra'), ('O', 'Otro')], default='I', max_length=1)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('costo_unitario', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('venta_unitario', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Item de Presupuesto',
                'verbose_name_plural': 'Items de Presupuesto',
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True, verbose_name='N° Presupuesto')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='borrador', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('descuento_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('forma_pago', models.CharField(choices=[('50_50', '50% anticipo, 50% día del evento'), ('100_anticipo', '100% anticipado'), ('30_70', '30% anticipo, 70% día del evento'), ('al_finalizar', 'Pago al finalizar el evento')], default='50_50', max_length=30)),
                ('validez_dias', models.PositiveIntegerField(default=15)),
                ('notas', models.TextField(blank=True, default='')),
                ('cliente_nombre', models.CharField(blank=True, default='', max_length=200)),
                ('cliente_email', models.CharField(blank=True, default='', max_length=200)),
                ('cliente_telefono', models.CharField(blank=True, default='', max_length=50)),
                ('cliente_direccion', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'ordering': ['-created_at'],
            },
        ),
    ]
