# Generated by Django 5.2.13 on 2026-04-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='cliente_rut',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
