# Generated by Django 5.2.13 on 2026-04-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_presupuesto_cliente_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='cliente_comuna',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='incluir_iva',
            field=models.BooleanField(default=False, verbose_name='Incluir IVA (19%)'),
        ),
    ]
