# Generated by Django 5.2.13 on 2026-04-09 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('eventos', '0004_presupuesto_cliente_comuna_presupuesto_incluir_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempresupuesto',
            name='producto_catalogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_presupuesto', to='catalogo.productocatalogo'),
        ),
    ]
