# Generated by Django 5.2.13 on 2026-04-11 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_alter_evento_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempresupuesto',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='itempresupuesto',
            name='venta_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
