# Generated by Django 5.2.13 on 2026-04-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_add_en_espera_estado_presupuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='es_externo',
            field=models.BooleanField(default=False, verbose_name='Origen Externo (Web)'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='estado',
            field=models.CharField(choices=[('prospecto', 'Prospecto'), ('presupuestado', 'Presupuestado'), ('confirmado', 'Confirmado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='presupuestado', max_length=20),
        ),
    ]
