# Generated by Django 5.2.13 on 2026-04-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_evento_es_externo_alter_evento_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='stock_procesado',
            field=models.BooleanField(default=False, verbose_name='Stock deducido'),
        ),
    ]
