# Generated by Django 5.2.13 on 2026-04-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=100)),
                ('titular', models.CharField(max_length=200)),
                ('rut', models.CharField(max_length=20)),
                ('numero_cuenta', models.CharField(max_length=50)),
                ('tipo_cuenta', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dato de Transferencia',
                'verbose_name_plural': 'Datos de Transferencia',
                'ordering': ['-activo', '-created_at'],
            },
        ),
    ]
