# Generated by Django 5.2.13 on 2026-04-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0003_datostransferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='evidencia',
            field=models.FileField(blank=True, null=True, upload_to='pagos/evidencia/', verbose_name='Evidencia de Transferencia'),
        ),
    ]
