# Generated by Django 5.2.13 on 2026-04-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0004_pago_evidencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(db_index=True, verbose_name='Fecha del Pago'),
        ),
    ]
