# Generated by Django 5.2.13 on 2026-04-21 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(choices=[('hero_video', 'Hero — Video principal'), ('hero_imagen', 'Hero — Imagen fallback'), ('nosotros_banner', 'Nosotros — Banner principal'), ('nosotros_foto1', 'Nosotros — Foto cocina/interior'), ('nosotros_foto2', 'Nosotros — Foto producto/tabla'), ('galeria', 'Galería — Foto (se pueden subir varias)')], max_length=30)),
                ('tipo', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video')], max_length=10)),
                ('archivo', models.FileField(upload_to='website/')),
                ('label', models.CharField(blank=True, help_text='Texto opcional para galería', max_length=100)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden en galería')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Media del Sitio Web',
                'verbose_name_plural': 'Media del Sitio Web',
                'ordering': ['seccion', 'orden'],
            },
        ),
    ]
