# Generated by Django 5.2.13 on 2026-04-22 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_api', '0002_mediaasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_marca', models.CharField(default='KRUXEL', max_length=100)),
                ('eslogan', models.CharField(default='Banquetería & Repostería', max_length=200)),
                ('logo', models.ImageField(blank=True, help_text='Logo opcional. Si no se sube, se usa el nombre como texto.', null=True, upload_to='website/logo/')),
                ('hero_subtitulo', models.CharField(default='Arte en cada evento', max_length=200)),
                ('footer_copyright', models.CharField(default='Banquetería & Repostería. Todos los derechos reservados.', max_length=300)),
                ('email_contacto', models.EmailField(default='contacto@kruxel.cl', max_length=254)),
                ('telefono', models.CharField(default='+56 9 0000 0000', max_length=30)),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com/kruxel')),
                ('instagram_usuario', models.CharField(blank=True, default='@kruxel', max_length=100)),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com/kruxel')),
                ('facebook_usuario', models.CharField(blank=True, default='KRUXEL', max_length=100)),
                ('whatsapp', models.CharField(blank=True, default='', max_length=30)),
            ],
            options={
                'verbose_name': 'Configuración del Sitio',
                'verbose_name_plural': 'Configuración del Sitio',
            },
        ),
    ]
