# Generated by Django 5.2.13 on 2026-04-22 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_api', '0003_configuracionsitio'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='nosotros_texto1',
            field=models.TextField(default='En KRUXEL creamos experiencias gastronómicas únicas para cada celebración. Desde bodas íntimas hasta grandes eventos corporativos, nuestra cocina combina técnica de alta cocina con ingredientes locales de temporada.'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='nosotros_texto2',
            field=models.TextField(default='Cada detalle importa — desde la selección de ingredientes hasta la presentación final — porque sabemos que los momentos que vivís merecen algo verdaderamente especial.'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='nosotros_titulo',
            field=models.CharField(default='Pasión que se transforma en sabor', max_length=200),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='stat1_label',
            field=models.CharField(default='Años de experiencia', max_length=100),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='stat1_num',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='stat2_label',
            field=models.CharField(default='Eventos realizados', max_length=100),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='stat2_num',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='stat3_label',
            field=models.CharField(default='Chefs especializados', max_length=100),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='stat3_num',
            field=models.PositiveIntegerField(default=12),
        ),
    ]
