# Generated by Django 5.2.13 on 2026-04-23 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_api', '0004_configuracionsitio_nosotros_texto1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsitio',
            name='email_contacto',
            field=models.EmailField(default='contacto@ryfbanqueteria.cl', max_length=254),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='facebook_url',
            field=models.URLField(blank=True, default='https://facebook.com/ryfbanqueteria'),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='facebook_usuario',
            field=models.CharField(blank=True, default='RyF banqueteria', max_length=100),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='instagram_url',
            field=models.URLField(blank=True, default='https://instagram.com/ryfbanqueteria'),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='instagram_usuario',
            field=models.CharField(blank=True, default='@ryfbanqueteria', max_length=100),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='nombre_marca',
            field=models.CharField(default='RyF banqueteria', max_length=100),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='nosotros_texto1',
            field=models.TextField(default='En RyF banqueteria creamos experiencias gastronómicas únicas para cada celebración. Desde bodas íntimas hasta grandes eventos corporativos, nuestra cocina combina técnica de alta cocina con ingredientes locales de temporada.'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='seccion',
            field=models.CharField(choices=[('hero_video', 'Hero — Video principal'), ('hero_imagen', 'Hero — Imagen fallback'), ('nosotros_banner', 'Nosotros — Banner principal'), ('nosotros_foto1', 'Nosotros — Foto cocina/interior'), ('nosotros_foto2', 'Nosotros — Foto producto/tabla'), ('galeria', 'Galería — Foto (se pueden subir varias)'), ('galeria_video', 'Galería — Video showcase (después de fotos)')], max_length=30),
        ),
    ]
