# Generated by Django 5.2.13 on 2026-04-09 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('categoria', models.CharField(choices=[('reposteria', 'Repostería'), ('banqueteria', 'Banquetería'), ('cocteleria', 'Coctelería'), ('bebidas', 'Bebidas'), ('otro', 'Otro')], default='otro', max_length=30)),
                ('precio_venta', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto de Catálogo',
                'verbose_name_plural': 'Productos de Catálogo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RecetaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usado_en_recetas', to='inventario.producto')),
                ('producto_catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='catalogo.productocatalogo')),
            ],
            options={
                'verbose_name': 'Item de Receta',
                'verbose_name_plural': 'Items de Receta',
            },
        ),
    ]
