# Generated by Django 5.2.13 on 2026-04-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productocatalogo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='catalogo/'),
        ),
    ]
