# Generated by Django 5.2.13 on 2026-04-09 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Gasto')),
                ('categoria', models.CharField(choices=[('arriendo', 'Arriendo / Bodega'), ('sueldos', 'Sueldos / Honorarios'), ('servicios', 'Servicios Públicos (Luz, Agua, Gas)'), ('insumos_fijos', 'Insumos de Limpieza/Oficina'), ('marketing', 'Marketing / Publicidad'), ('seguros', 'Seguros / Patentes'), ('mantenimiento', 'Mantenimiento'), ('suscripciones', 'Suscripciones (ERP, Software)'), ('otro', 'Otro')], default='otro', max_length=30)),
                ('monto', models.DecimalField(decimal_places=0, max_digits=12)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], default='pendiente', max_length=20)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='gastos/comprobantes/')),
                ('observaciones', models.TextField(blank=True, default='')),
                ('mes', models.PositiveIntegerField(blank=True, null=True)),
                ('anio', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gasto Fijo',
                'verbose_name_plural': 'Gastos Fijos',
                'ordering': ['fecha_vencimiento', 'nombre'],
            },
        ),
    ]
