# Generated by Django 5.2.13 on 2026-04-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastofijo',
            name='anio',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='gastofijo',
            name='mes',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
