# Generated by Django 5.2.13 on 2026-04-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste')], max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_nuevo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('motivo', models.CharField(blank=True, default='', max_length=300)),
                ('referencia_evento', models.CharField(blank=True, default='', max_length=200, verbose_name='Evento Relacionado')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Movimiento de Stock',
                'verbose_name_plural': 'Movimientos de Stock',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('categoria', models.CharField(choices=[('ingrediente', 'Ingrediente'), ('insumo', 'Insumo'), ('descartable', 'Descartable'), ('bebida', 'Bebida'), ('equipamiento', 'Equipamiento'), ('otro', 'Otro')], default='ingrediente', max_length=20)),
                ('unidad', models.CharField(choices=[('kg', 'Kilogramo (kg)'), ('lt', 'Litro (lt)'), ('un', 'Unidad (un)'), ('docena', 'Docena'), ('caja', 'Caja'), ('bolsa', 'Bolsa'), ('bandeja', 'Bandeja'), ('paquete', 'Paquete')], default='un', max_length=10)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_compra', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Precio Compra (CLP)')),
                ('precio_venta', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Precio Venta (CLP)')),
                ('proveedor', models.CharField(blank=True, default='', max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
    ]
