# Generated by Django 4.2.30 on 2026-04-10 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Fotografía de perfil del usuario.', null=True, upload_to='avatars/'),
        ),
    ]
