# Generated by Django 5.2.13 on 2026-04-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginConfiguracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color1', models.CharField(default='#DE443B', help_text='Hex code for Color 1', max_length=7)),
                ('color2', models.CharField(default='#006BB4', help_text='Hex code for Color 2', max_length=7)),
                ('color3', models.CharField(default='#162325', help_text='Hex code for Color 3', max_length=7)),
                ('pixel_filter', models.IntegerField(default=745, help_text='Resolution filter (pixelation)')),
                ('is_rotate', models.BooleanField(default=False, help_text='Enable circular spin')),
                ('mouse_interaction', models.BooleanField(default=True, help_text='Enable mouse interaction')),
                ('spin_speed', models.FloatField(default=7.0)),
                ('contrast', models.FloatField(default=3.5)),
                ('lighting', models.FloatField(default=0.4)),
            ],
            options={
                'verbose_name': 'Configuración de Login',
                'verbose_name_plural': 'Configuraciones de Login',
            },
        ),
    ]
