# Generated by Django 5.2.13 on 2026-04-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_loginconfiguracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginconfiguracion',
            name='spin_amount',
            field=models.FloatField(default=0.25),
        ),
        migrations.AddField(
            model_name='loginconfiguracion',
            name='spin_ease',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='loginconfiguracion',
            name='spin_rotation',
            field=models.FloatField(default=-2.0),
        ),
    ]
