# Generated by Django 5.2.13 on 2026-04-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_add_spin_fields_to_login_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginconfiguracion',
            name='animation_type',
            field=models.CharField(choices=[('balatro', 'Balatro'), ('linewaves', 'Line Waves'), ('hyperspeed', 'Hyperspeed')], default='balatro', max_length=20),
        ),
    ]
