# Generated by Django 5.2.13 on 2026-04-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_add_animation_type_to_login_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginconfiguracion',
            name='lw_brightness',
            field=models.FloatField(default=0.2),
        ),
        migrations.AddField(
            model_name='loginconfiguracion',
            name='lw_color_cycle_speed',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='loginconfiguracion',
            name='lw_edge_fade_width',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='loginconfiguracion',
            name='lw_inner_line_count',
            field=models.IntegerField(default=32),
        ),
        migrations.AddField(
            model_name='loginconfiguracion',
            name='lw_mouse_influence',
            field=models.FloatField(default=2.0),
        ),
        migrations.AddField(
            model_name='loginconfiguracion',
            name='lw_outer_line_count',
            field=models.IntegerField(default=36),
        ),
        migrations.AddField(
            model_name='loginconfiguracion',
            name='lw_rotation',
            field=models.FloatField(default=-45.0),
        ),
        migrations.AddField(
            model_name='loginconfiguracion',
            name='lw_warp_intensity',
            field=models.FloatField(default=1.0),
        ),
    ]
