# Generated by Django 5.2.13 on 2026-04-23 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_loginconfiguracion_login_titulo_subtitulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisomodulo',
            name='modulo',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('eventos', 'Eventos'), ('presupuestos', 'Presupuestos'), ('cobros', 'Cobros'), ('gastos', 'Gastos'), ('inventario', 'Inventario'), ('catalogo', 'Catálogo'), ('reportes', 'Reportes'), ('configuracion', 'Configuración'), ('configuracion_login', 'Visual Login'), ('mantenedor', 'Mantenedor'), ('solicitudes', 'Solicitudes')], max_length=30),
        ),
    ]
